/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddIcon: typeof import('./src/components/svgs/AddIcon.vue')['default']
    BaseNotifications: typeof import('./src/components/BaseNotifications.vue')['default']
    BasePagination: typeof import('./src/components/BasePagination.vue')['default']
    CalenderIcon: typeof import('./src/components/svgs/CalenderIcon.vue')['default']
    ChatComponent: typeof import('./src/components/tickets/ChatComponent.vue')['default']
    ContactsCard: typeof import('./src/components/settings/ContactsCard.vue')['default']
    ControlQuantity: typeof import('./src/components/products/ControlQuantity.vue')['default']
    DataTableLoader: typeof import('./src/components/dataTableLoader.vue')['default']
    DeleteIcon: typeof import('./src/components/svgs/DeleteIcon.vue')['default']
    EditIcon: typeof import('./src/components/svgs/EditIcon.vue')['default']
    GDatePicker: typeof import('./src/components/GDatePicker.vue')['default']
    GlobalPopup: typeof import('./src/components/GlobalPopup.vue')['default']
    ListingHeader: typeof import('./src/components/listing/listingHeader.vue')['default']
    ListingItems: typeof import('./src/components/listing/listingItems.vue')['default']
    PermissionsCard: typeof import('./src/components/settings/PermissionsCard.vue')['default']
    PriceDiscount: typeof import('./src/components/products/PriceDiscount.vue')['default']
    ProductSales: typeof import('./src/components/ProductSales.vue')['default']
    RatingBar: typeof import('./src/components/RatingBar.vue')['default']
    Ratings: typeof import('./src/components/Ratings.vue')['default']
    ReplayCard: typeof import('./src/components/tickets/ReplayCard.vue')['default']
    ReviewRating: typeof import('./src/components/ReviewRating.vue')['default']
    RoleCard: typeof import('./src/components/settings/RoleCard.vue')['default']
    RoleHeader: typeof import('./src/components/settings/RoleHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StarRating: typeof import('./src/components/StarRating.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    TableFilters: typeof import('./src/components/tableFilters.vue')['default']
    Tabs: typeof import('./src/components/settings/Tabs.vue')['default']
    UserCard: typeof import('./src/components/settings/UserCard.vue')['default']
    UserProfile: typeof import('./src/components/settings/UserProfile.vue')['default']
    ViewChats: typeof import('./src/components/tickets/ViewChats.vue')['default']
    ViewHeader: typeof import('./src/components/tickets/ViewHeader.vue')['default']
    ViewIcon: typeof import('./src/components/svgs/ViewIcon.vue')['default']
    ViewRole: typeof import('./src/components/settings/ViewRole.vue')['default']
  }
}
