/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    GDatePicker: typeof import('./src/components/GDatePicker.vue')['default']
    ListingHeader: typeof import('./src/components/listing/listingHeader.vue')['default']
    ListingItems: typeof import('./src/components/listing/listingItems.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    VDatePicker: typeof import('./src/components/VDatePicker.vue')['default']
  }
}
